# Windows toolchain file for ARM GCC
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

# 直接使用 PATH 中的编译器
set(CMAKE_C_COMPILER "arm-none-eabi-gcc" CACHE INTERNAL "")
set(CMAKE_CXX_COMPILER "arm-none-eabi-g++" CACHE INTERNAL "")
set(CMAKE_ASM_COMPILER "arm-none-eabi-gcc" CACHE INTERNAL "")
set(CMAKE_EXE_LINKER_FLAGS "" CACHE INTERNAL "")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_C_COMPILER_WORKS 1)
set(CMAKE_CXX_COMPILER_WORKS 1)
set(CMAKE_ASM_COMPILER_WORKS 1)
